language: dart
sudo: false
dart:
  - "dev"
  - "stable"
  - "2.0.0"

dart_task:
- dartanalyzer: '--fatal-warnings lib/ test/'
- test: --platform vm

matrix:
  allow_failures:
    - dart: "dev"

script:
  - dartanalyzer --fatal-warnings lib/ test/
  - pub run test --platform=vm

#after_success:
#  # Check coverage
#  - bash <(curl -s https://codecov.io/bash) -f build/coverage/coverage.lcov