language: dart
sudo: false
dart:
  - "stable"
  - "1.15.0"
  - "1.14.0"
  - "dev"

matrix:
  allow_failures:
    - dart: "dev"

script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
  - pub run dart_dev coverage --no-html

after_success:
  # Check coverage
  - bash <(curl -s https://codecov.io/bash) -f build/coverage/coverage.lcov