---
include: package:lint/analysis_options.yaml

linter:
  rules:
    - camel_case_types

analyzer:
  enable-experiment:
    - non-nullable
    
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false