name: money2
description: Money and Currency classes with fixed precision maths, parsing and formating.
    (Money.parse("$2010.00") * 10).format("S CC#,##0") -> $ US20,100
version: 1.2.2
homepage: https://github.com/noojee/money.dart
authors: 
  - LitGroup LLC <opensource@litgroup.ru>
  - Noojee IT Pty Ltd <bsutton@noojee.com.au>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies: 
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.1
