name: money2
description: A user friendly implementation of LitGroup's Dart Money.
  Provides Money and Currency classes with fixed precision maths operations and a nice Money formatter.
version: 1.0.0-beta.6
homepage: https://github.com/noojee/money.dart
authors: 
  - LitGroup LLC <opensource@litgroup.ru>
  - Noojee IT Pty Ltd <bsutton@noojee.com.au>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies: 
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.1
