name: money
description: >
  "Dart implementation of Fowler's Money pattern"
version: 0.1.1
author: Roman Shamritskiy <roman@litgroup.ru>
homepage: https://github.com/dartiny/money
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
