name: money
description: >
  Dart implementation of Fowler's Money pattern
version: 0.2.0
author: Roman Shamritskiy <roman@litgroup.ru>
homepage: https://github.com/litgroup/money.dart
environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ">=1.3.0 <2.0.0"