name: money2
description: Money and Currency classes with fixed precision maths operations and Formating.
    Money.fromtInt(1000).format("SCC#,##0.00") -> $US10.00
version: 1.1.0
homepage: https://github.com/noojee/money.dart
authors: 
  - LitGroup LLC <opensource@litgroup.ru>
  - Noojee IT Pty Ltd <bsutton@noojee.com.au>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies: 
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.1
