name: money
description: The Dart implementation of Fowler's Money pattern.
version: 1.0.0-alpha.2
repository: https://github.com/litgroup/money.dart

environment:
  sdk: ^3.1.3

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
